[package]
name = "ecs"
authors = ["Swiiz"]
version = "0.1.0"
edition = "2021"

[dependencies]
generational-arena = { version = "0.2.8", features = ["serde"] }
impl-trait-for-tuples = "0.2.2"
serde = { version = "1.0.209", features = ["derive"] }